/**
 * CSS validity for Afterglow.
 *
 * The standard config is the baseline. Each exception below is a place where
 * the standard rule is actively wrong for a themed token system, not a place
 * where the rule was inconvenient.
 */

export default {
  extends: 'stylelint-config-standard',

  rules: {
    // Afterglow's own tokens are --ag-*. Assigning an Obsidian variable is also
    // a custom property declaration, so this pattern doubles as a layering
    // constraint: only the mapping layer may declare anything else, and the
    // override below is what grants it that. A stray --nav-item-color in the
    // role layer is a lint failure.
    'custom-property-pattern': '^ag-[a-z0-9]+(-[a-z0-9]+)*$',

    // Font family names are proper nouns. "Palatino" and "SFMono-Regular" are
    // how the fonts are actually named; lowercasing them would not match.
    'value-keyword-case': null,

    // Tokens are grouped into labelled runs — grounds, text, rules, states —
    // separated by blank lines and comments. That grouping is the readability
    // of the file, and both of these rules would flatten it.
    'custom-property-empty-line-before': null,
    'comment-empty-line-before': null,
    'declaration-empty-line-before': null,
  },

  overrides: [
    {
      // The mapping layer exists to declare Obsidian's variables, so it is the
      // one file exempt from the --ag-* naming pattern.
      files: ['**/src/04-obsidian.css'],
      rules: {
        'custom-property-pattern': null,
      },
    },
    {
      // theme.css is generated by concatenating src/, so the mode selectors
      // appear once per layer by design: palette, then roles. Enforcing unique
      // selectors here would be enforcing a single-layer architecture.
      files: ['**/theme.css'],
      rules: {
        'no-duplicate-selectors': null,
        'custom-property-pattern': null,
      },
    },
  ],

  ignoreFiles: ['node_modules/**'],
};
